# Site settings
title: 1924 Pieces of Me
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://1924piecesofme.com" # the base hostname & protocol for your site

author:
  fullname: The Artist Embodied
  email: me@1924piecesofme.com
  youtube: https://www.youtube.com/channel/UCN0AC9XH3ED7TQBigOZYxrQ
  twitter: 1924_me

# google_analytics: 'UA-XXXXXXXX-X'

# Syntax highlighting
highlightstyle: ''
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]

# Handling Reading
exclude: ["README.md", "README.html"]

prose:
  metadata:
    _includes:
      - name: "title"
        field:
          element: "hidden"
          label: "title"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: true
    contact.md:
      - name: "subtitle"
        field:
          element: "text"
          label: "subtitle"
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "hidden"
          value: "/contact"
    about.md:
      - name: "subtitle"
        field:
          element: "text"
          label: "subtitle"
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "hidden"
          value: "/about"
    _posts:
      - name: "date"
        field:
          element: "hidden"
          value: CURRENT_DATETIME
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "subtitle"
        field:
          element: "text"
          label: "subtitle"
      - name: "layout"
        field:
          element: "hidden"
          label: "layout"
      - name: "categories"
        field:
          element: "hidden"
          label: "categories"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: true
  media: "img"
  ignore:
    - /_sass
    - /_data
    - /_includes/category
    - /_includes/externals
    - /_includes/meta_tags
    - /_includes/page
    - /_includes/post
    - /_includes/header.html
    - /_layouts
    - /img
    - /assets
    - /css
    - /categories
    - CNAME
    - sitemap.xml
    - feed.xml
    - readme.html
    - README.md
    - .gitignore
    - robots.txt
    - 404.html
    - index.html
    - apple-touch-icon-114x114.png
    - apple-touch-icon-120x120.png
    - apple-touch-icon-144x144.png
    - apple-touch-icon-152x152.png
    - apple-touch-icon-57x57.png
    - apple-touch-icon-60x60.png
    - apple-touch-icon-72x72.png
    - apple-touch-icon-76x76.png
    - favicon-128.png
    - favicon-16x16.png
    - favicon-196x196.png
    - favicon-32x32.png
    - favicon-96x96.png
    - favicon.ico
    - general-social-share-preview.png
    - github-social-preview.png
    - logo-final-twitter-header.png
    - logo-square.png
    - logo-transparent.png
    - logo-youtube-channel-art.png
    - logo.png
    - mstile-144x144.png
    - mstile-150x150.png
    - mstile-310x150.png
    - mstile-310x310.png
    - mstile-70x70.png
    - twitter-card.png
    # REMOVE THIS LINE TO EDIT THE CONFIG
    - _config.yml

# Build settings
highlighter: null
markdown: kramdown
plugins:
  - jekyll-sitemap
